# Generated by Django 4.1.4 on 2023-05-13 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 21, 30, 409443), verbose_name='Time published'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 21, 30, 414434), verbose_name='Time published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 21, 30, 411445), verbose_name='Time published'),
        ),
    ]
