# Generated by Django 4.1.4 on 2023-05-21 00:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_alter_news_pub_date_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 3, 22, 9, 764283), verbose_name='Time published'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 3, 22, 9, 772508), verbose_name='Time published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 3, 22, 9, 768531), verbose_name='Time published'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mail', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 5, 21, 3, 22, 9, 774537), verbose_name='Time sent')),
                ('appeal', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'support',
            },
        ),
    ]
